version: '3'
services:
  redisearch:
    image: "redislabs/redisearch:1.6.5"
    ports:
      - "6379:6379"
  redisgraph:
    image: "redislabs/redisgraph:1.99.8"
    ports:
      - "6380:6379"
  redisgraph-old:
    image: redislabs/redisgraph:1.2.2
    ports:
      - "6381:6379"
  redistimeseries:
    image: "redislabs/redistimeseries:1.2.0"
    ports:
      - "6382:6379"
  beerloader-search:
    build: ./beerloader-search/.
    depends_on:
      - redisearch
    command: ['import.py', '--url', 'redis://redisearch:6379']
  beerloader-graph:
    build: ./beerloader-graph/.
    depends_on:
      - redisgraph
    environment:
      - REDIS_HOST=redisgraph
    command: ['python', 'loader.py']
  beerloader-graph-2:
    build: ./beerloader-graph/.
    depends_on:
      - redisgraph-old
    environment:
      - REDIS_HOST=redisgraph-old
    command: ['python', 'loader.py']
  redisinsight:
    image: "redislabs/redisinsight:1.2.0-rc1"
    ports:
      - "8001:8001"
  dbloader:
    build: ./dbloader/.
    depends_on: 
      - redisinsight
      - redisearch
      - redisgraph
      - redisgraph-old
      - redistimeseries
    environment:
      - APP_URL=http://redisinsight:8001
    command: ['python', 'dbloader.py', "--db_urls=redisearch:6379;redistimeseries:6379;redisgraph:6379;redisgraph-old:6379"]
